### ISSUE TITLE
Implement simple data writer : output formats: jpg, mp3, numpy, mp4

### ISSUE THREAD

**Issue by iejMac** [iejMac/video2dataset#1]
https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.px7ldb9e9fjj

DoD: the data writer can emit jpg, numpy, mp3 or mp4 as files or webdataset

Should work like this
```
writer = Writer("shard_001.tar")
writer({"mp3": b"..."})
```

take a look at https://github.com/rom1504/img2dataset/blob/main/img2dataset/writer.py for reference

**Comment by rom1504** [comment]
simple data writer is there, will create further issues for more features
