### ISSUE TITLE
example of training usage

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#10]
* https://github.com/lucidrains/phenaki-pytorch
* https://github.com/lucidrains/audiolm-pytorch
* https://github.com/LAION-AI/temporal-embedding-aggregation

DoD: a .md is created in the repo to say some example / same info in gdoc

https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.uwyt4zqe1dgy

**Comment by iejMac** [comment]
being used in video clip and generative projects, done
