### ISSUE TITLE
Can't use s3 url as output_folder

### ISSUE THREAD

**Issue by marianna13** [iejMac/video2dataset#113]
Hi! I can't download media with video2dataset to s3. Here's my code:

```python
if __name__ == '__main__':

    output_dir = 's3://s-laion/video2dataset_test_paltforms/'

    video2dataset(
        url_list='output.parquet',
        input_format='parquet',
        output_format='webdataset',
        output_folder=output_dir,
        encode_formats={"video": "mp4", "audio": "mp3"},
    ) 
```

Thank you!

**Comment by iejMac** [comment]
@marianna13 can you say more about what error you're getting?

**Comment by marianna13** [comment]
Hi! @iejMac ! I'm not getting any error message - the data just keeps being saved to the disk (in this case to the `s-laion` folder) but not to s3 :(

**Comment by iejMac** [comment]
You need to give me more info, I tried reproducing but this works:
```python3
from video2dataset import video2dataset

if __name__ == '__main__':

    output_dir = 's3://s-laion/video2dataset_test_paltforms/'

    video2dataset(
        url_list='/fsx/iejmac/datasets/acav100m/ACAV_test.parquet',
        input_format='parquet',
        output_format='webdataset',
        output_folder=output_dir,
        url_col="videoLoc",
        caption_col="title",
        encode_formats={"video": "mp4", "audio": "mp3"},
    )
```

**Comment by marianna13** [comment]
@iejMac I ran the very same code as above and still it downloads to disk: 
![image](https://user-images.githubusercontent.com/43296932/223969037-46f57d67-5706-4c9e-9929-a0d8c3fe1dd2.png)
Maybe it's my s3 configuration issue?
Anyway thank you very much, now I know that it might be problem on my side rather than video2dataset issue :)

**Comment by iejMac** [comment]
downloading YouTube videos worked fine though
