### ISSUE TITLE
set local rank from startup script

### ISSUE THREAD

**Issue by ablattmann** [iejMac/video2dataset#141]
add `os.environ['LOCAL_RANK'] = subtask_id` [here](https://github.com/iejMac/video2dataset/blob/c8ab4cad5fb4df2130c97ed321dcf78499a24e36/video2dataset/slurm_executor.py#L61)

**Comment by ablattmann** [comment]
@danielmend

**Comment by iejMac** [comment]
done - https://github.com/iejMac/video2dataset/blob/121b9bbcb9506a06218b6ae06bf461730278e3ae/video2dataset/slurm_executor.py#L61
