### ISSUE TITLE
data_reader.py: add reading from local

### ISSUE THREAD

**Issue by iejMac** [iejMac/video2dataset#152]
there are datasets that just offer the videos in a .zip file (typically benchmark datasets). For that its nice to just extract it all, organize the parquet and then execute it as if it were on the web I just need to add some code that checks if it's a local file and if it is then pass it through some BytesReader or something idk.

Main task: detection between mp4 LINK or mp4 FILE

**Comment by rom1504** [comment]
Might be interesting to investigate support of fsspec of file/url and also
of archives. Maybe it's not needed to dezip

**Comment by iejMac** [comment]
I have this https://github.com/iejMac/video2dataset/pull/153 as a temporary solution but I guess something more general with fsspec would probably be better
