### ISSUE TITLE
Documentation and packaging

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#16]
DoD: basic API doc in readme, one example available

**Comment by rom1504** [comment]
on this I need  you need to create a token there https://pypi.org/manage/account/token/ and put it in there https://github.com/iejMac/video2dataset/settings/secrets/actions/new name it PYPI_PASSWORD
@iejMac please

**Comment by iejMac** [comment]
Only need to add the example for this.

**Comment by iejMac** [comment]
@rom1504 is this complete?

**Comment by rom1504** [comment]
Yeah
