### ISSUE TITLE
fps subsampler

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#21]
https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.w8r1nm2s7fy1

DoD: fps subsampler was implemented and benchmarked

```
fps_subsampler = FpsSubsampler()

subsampled = FpsSubsampler(video)
```

**Comment by iejMac** [comment]
https://github.com/iejMac/video2dataset/pull/89
