### ISSUE TITLE
Error; failed to download

### ISSUE THREAD

**Issue by shameforest** [iejMac/video2dataset#239]
Any idea what I can do?

Unable to exract initial player response
unable to extract yt initial data
Failed to download youtube videos:

Sharding file number 1 of 1 called /workspace/Footage/videos.csv
0it [00:00, ?it/s]File sharded in 1 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
WARNING: icWAsUDqClI: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
WARNING: tFR_ox1E49I: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
WARNING: kqwivGOFCco: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
1it [01:00, 60.16s/it]
worker  - success: 1.000 - failed to download: 0.000 - failed to resize: 0.000 - videos per sec: 0 - bytes per sec: 2202259 - count: 4
total   - success: 1.000 - failed to download: 0.000 - failed to resize: 0.000 - videos per sec: 0 - bytes per sec: 2202259 - count: 4
root@880369bc73cc:/workspace/Footage# yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
root@880369bc73cc:/workspace/Footage# video2dataset --url_list="videos.csv" --url_col="url" --caption_col="caption" --output_folder="dataset"
Starting the downloading of this file
Sharding file number 1 of 1 called /workspace/Footage/videos.csv
0it [00:00, ?it/s]File sharded in 0 shards
Downloading starting now, check your bandwidth speed (with bwm-ng)your cpu (with htop), and your disk usage (with iotop)!
0it [00:00, ?it/s]
root@880369bc73cc:/workspace/Footage#

**Comment by iejMac** [comment]
Can you check the output dataset? It seems the logger says you have 100% success rate so it should've worked:

```
total - success: 1.000 - failed to download: 0.000 - failed to resize: 0.000 - videos per sec: 0 - bytes per sec: 2202259 - count: 4
```

With yt-dlp it produces these Warnings however it doesn't always mean the video didn't succeed to download
