### ISSUE TITLE
implement input sharder

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#24]
https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.g59sfbda6v9c

DoD: input sharder implemented and tested

**Comment by iejMac** [comment]
how do we do this? is this already done in img2dataset?

**Comment by rom1504** [comment]
Yeah it's https://github.com/rom1504/img2dataset/blob/main/img2dataset/reader.py#L139

Today in img2dataset only one input file is shared at a time, but it might change in the future

Here I'd suggest to shard everything beforehand

I think that file from img2dataset can be mostly copy pasted

**Comment by rom1504** [comment]
done
