### ISSUE TITLE
Unable to download webpage 

### ISSUE THREAD

**Issue by Khushxx** [iejMac/video2dataset#240]
App version: 1.10.0-beta.3 (10920)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.crunchyroll.com/watch/G0DUNJ2JP?utm_medium=android&utm_source=share
ERROR: [crunchyroll] G0DUNJ2JP: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by rom1504** [comment]
I suggest you do what the error says

**Comment by Khushxx** [comment]
> 

And what the error said

**Comment by rom1504** [comment]
"please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template."
