### ISSUE TITLE
Rename implementations to fit naming of design

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#25]
https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.iql4z2bvephh

* input sharder
* data reader
* subsampler
* data writer

downloader should fit into data reader

**Comment by iejMac** [comment]
@rom1504 what do you mean in this? like rename the classes or the scripts?

**Comment by rom1504** [comment]
Yeah i mean to have file with
- input sharder
- data reader
- subsampler
- data writer

And nothing else. That's the most important part, nothing else.

**Comment by rom1504** [comment]
done
