### ISSUE TITLE
Failed to download: 0.000 messages when downloading

### ISSUE THREAD

**Issue by minuenergy** [iejMac/video2dataset#268]
I was follow with this

video2dataset:
pip install video2dataset
Example downloading [script](https://github.com/iejMac/video2dataset/blob/main/examples/download_webvid.sh). video2dataset has many options for subsampling the input data (FPS, resolution, cut detection, optical flow, etc.) so this script can be greatly modified to enrich/standardize the output dataset.
Load into nicely batched tensors like [this](https://github.com/iejMac/video2dataset/blob/main/examples/dataloader_example.py)

and I got this log but it does downloading. so I confuse this message
is it good to ignore those messages? 

![image](https://github.com/iejMac/video2dataset/assets/72018553/9335eaba-bf6d-4f8b-85e5-8cfa856b0f5e)

**Comment by rom1504** [comment]
it means 0% failed to download. Seems to work as expected
