### ISSUE TITLE
Implement the flow

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#3]
video url table -> input sharder -> data reader -> subsampler -> data writer

https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.5yrpnwfijqfb

DoD: should run and have simple tests

**Comment by iejMac** [comment]
everything but the sharder/resizer is implemented. Currently you can take a video/metadata url table and turn it into a webdataset (or files) with the mp4's, txt's, and json

**Comment by rom1504** [comment]
done except subsampler, moving that to another issue
