### ISSUE TITLE
basic audio reader

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#36]
@marianna13

let's try and put this into https://github.com/iejMac/video2dataset/blob/main/video2dataset/data_reader.py

**Comment by rom1504** [comment]
maybe a subsampler as well if you need to do transformations

**Comment by marianna13** [comment]
My downloader will work the same for a local file (if you provide a filename instead of url ): https://github.com/marianna13/video2dataset/blob/1ff5be920ca5c2c45865d14c60956d5de968b40c/video2dataset/downloader.py#L11
