### ISSUE TITLE
Subsampler: Audio encoding 

### ISSUE THREAD

**Issue by rom1504** [iejMac/video2dataset#8]
https://docs.google.com/document/d/1_TD2KQLkEegszq4Eip568fc6cWnh9h0Jqj4Lc88t9Y0/edit#bookmark=id.w8r1nm2s7fy1

What's the best way to do this

@marianna13

* Soundfile
* Ffmpeg

Input: audio from audio or video file
Output : mp3 or similar
Options: quality, segment lengths, encoding kind, ...

DoD: basic audio subsampler implemented and merged

**Comment by marianna13** [comment]
## Support for audio streams
Both [soundfile](https://github.com/bastibe/python-soundfile) and ffmpeg (ffprobe) can utilize audio streams (bytes). But in the case of ffmpeg there're less intermediate steps. 

## Dependencies
Soundfile can only be used with [librosa](https://github.com/librosa/librosa) lib that adds another dependency.

## Supported codecs:
- [Soundfile](http://www.mega-nerd.com/libsndfile/#Features)
- [ffmpeg](https://ffmpeg.org/ffprobe-all.html#Audio-Codecs)

ffmpeg supports more formats.

## Input formats
The input can be either an audio URL or a path to audio file.

## Output formats
The info that's possible to extract (again, with ffmpeg - it's less steps):
- sample rate
- format
- duration
- no of channels
- etc

Example: `{'format': 'mp3', 'channels': 1, 'duration': '802.108000', 'sample_rate': '16000'}`.

## Conclusion
It's better to use ffmpeg (ffprobe).
