### ISSUE TITLE
add logging

### ISSUE THREAD

**Issue by iejMac** [iejMac/video2dataset#9]

**Comment by rom1504** [comment]
what is this

**Comment by iejMac** [comment]
add logging

**Comment by iejMac** [comment]
maybe that's what I should've called it

**Comment by iejMac** [comment]
@rom1504 maybe we should add a list of what we should log and what logging levels we want to add

**Comment by rom1504** [comment]
might be worth doing something like <https://github.com/rom1504/img2dataset/blob/main/img2dataset/logger.py> to decouple worker from logging

**Comment by rom1504** [comment]
ie I think it should be mostly metrics based

**Comment by rom1504** [comment]
done now, but can be improved
